# Site settings
title: 「放肆的肆」

description: > # www

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
permalink: /:year:month:day.html
